# Generated by Django 4.1.5 on 2023-01-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addcasemodel',
            fields=[
                ('add_id', models.AutoField(primary_key=True, serialize=False)),
                ('Child', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('eyecolor', models.CharField(max_length=50)),
                ('haricolor', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'add_cases',
            },
        ),
    ]
