# Generated by Django 4.1.5 on 2023-01-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_registercasemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercasemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
