# Generated by Django 4.1.5 on 2023-01-17 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_registercasemodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='userfeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall', models.IntegerField(help_text='data', null=True)),
                ('caseregister', models.IntegerField(help_text='responding', null=True)),
                ('suggestion', models.CharField(help_text='suggestion', max_length=400, null=True)),
                ('sentiment', models.CharField(help_text='sentiment', max_length=50, null=True)),
                ('feedback2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'userfeedback_details',
            },
        ),
    ]
