# Generated by Django 4.1.5 on 2023-01-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercasemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel'),
        ),
    ]
