# Generated by Django 4.1.5 on 2023-01-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_registercasemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registercasemodel',
            old_name='user',
            new_name='user_case',
        ),
    ]
