# Generated by Django 4.1.5 on 2023-01-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_rename_user_registercasemodel_user_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercasemodel',
            name='status',
            field=models.CharField(default='Not Found', max_length=50),
        ),
    ]
